# Generated by Django 6.0.5 on 2026-05-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='teaser_video',
            field=models.FileField(blank=True, null=True, upload_to='skill_videos/'),
        ),
    ]
