from django.urls import path
from . import views

urlpatterns = [
    path('', views.login_view, name='login'),
    path('signup/', views.signup_view, name='signup'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('marketplace/', views.marketplace_view, name='marketplace'),
    path('profile/', views.profile_view, name='profile'),
    path('profile/<int:user_id>/', views.view_profile, name='view_profile'),
    path('post-skill/', views.post_skill_view, name='post_skill'),
    path('matches/', views.matches_view, name='matches'),
    path('chat/', views.chat_list_view, name='chat_list'),
    path('chat/<int:user_id>/', views.chat_view, name='chat'),
    path('swap-requests/', views.swap_requests_view, name='swap_requests'),
    path('swap-request/<int:request_id>/accept/', views.accept_swap, name='accept_swap'),
    path('swap-request/<int:request_id>/reject/', views.reject_swap, name='reject_swap'),
    path('request-swap/<int:skill_id>/', views.request_swap, name='request_swap'),
    path('reviews/', views.reviews_view, name='reviews'),
    path('review/<int:user_id>/', views.submit_review, name='submit_review'),
    path('notifications/', views.notifications_view, name='notifications'),
    path('admin-panel/', views.admin_dashboard, name='admin_dashboard'),
    path('admin-panel/users/', views.admin_users, name='admin_users'),
    path('admin-panel/users/delete/<int:user_id>/', views.admin_delete_user, name='admin_delete_user'),
    path('admin-panel/skills/', views.admin_skills, name='admin_skills'),
    path('admin-panel/skills/delete/<int:skill_id>/', views.admin_delete_skill, name='admin_delete_skill'),
    path('admin-panel/requests/', views.admin_requests, name='admin_requests'),
    path('admin-panel/requests/approve/<int:request_id>/', views.admin_approve_request, name='admin_approve_request'),
    path('admin-panel/requests/reject/<int:request_id>/', views.admin_reject_request, name='admin_reject_request'),
    path('admin-panel/reports/', views.admin_reports, name='admin_reports'),
]
